Repository emichael/dslabs, pull requests merged in 2022-04, with the labels that each got.

#29 Incorporate SearchSettings in the new debugger
  framework/tst/dslabs/framework/testing/junit/BaseJUnitTest.java
  framework/tst/dslabs/framework/testing/newviz/DebuggerWindow.java
  framework/tst/dslabs/framework/testing/newviz/FlatLaf.properties
  framework/tst/dslabs/framework/testing/newviz/SingleNodePanel.java
  framework/tst/dslabs/framework/testing/newviz/Utils.java
  framework/tst/dslabs/framework/testing/visualization/VizClient.java
Labels: enhancement, component:visualizer

#30 Use most recent SearchSettings in new debugger
  framework/tst/dslabs/framework/testing/junit/BaseJUnitTest.java
Labels: bug, component:visualizer

#32 Line wrap predicate names
  framework/tst/dslabs/framework/testing/newviz/DebuggerWindow.java
Labels: component:visualizer

#31 Add the ability to save and replay traces generated by invariant violations
  .gitignore
  Makefile
  framework/tst-self/dslabs/framework/testing/utils/CloningTest.java
  framework/tst/dslabs/framework/testing/AbstractState.java
  framework/tst/dslabs/framework/testing/ClientWorker.java
  framework/tst/dslabs/framework/testing/Event.java
  framework/tst/dslabs/framework/testing/StateGenerator.java
  framework/tst/dslabs/framework/testing/StatePredicate.java
  framework/tst/dslabs/framework/testing/junit/BaseJUnitTest.java
  framework/tst/dslabs/framework/testing/junit/CheckSavedTracesTest.java
  framework/tst/dslabs/framework/testing/junit/DSLabsTestCore.java
  framework/tst/dslabs/framework/testing/junit/DSLabsTestListener.java
  framework/tst/dslabs/framework/testing/junit/ReplaySavedTracesTestListener.java
  framework/tst/dslabs/framework/testing/junit/TraceReplaySearch.java
  framework/tst/dslabs/framework/testing/search/Search.java
  framework/tst/dslabs/framework/testing/search/SearchState.java
  framework/tst/dslabs/framework/testing/search/SerializableTrace.java
  framework/tst/dslabs/framework/testing/utils/ClassSearch.java
  framework/tst/dslabs/framework/testing/utils/GlobalSettings.java
  framework/tst/dslabs/framework/testing/utils/SerializablePredicate.java
  framework/tst/dslabs/framework/testing/utils/SerializableSupplier.java
  framework/tst/dslabs/framework/testing/visualization/SavedTraceViz.java
  handout-files/.gitignore
  handout-files/Makefile
  handout-files/README.md
  handout-files/run-tests.py
Labels: enhancement
